vich_uploader:
  db_driver: orm

  mappings:
    files:
      uri_prefix: /uploads
      upload_destination: '%kernel.project_dir%/data/uploads'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
