version: "3.4"

services:
  caddy:
    ports:
      - ${SERVER_PORT}:80

  mysql:
    ports:
      - ${MYSQL_PORT}:3306

  mercure:
    ports:
      - ${MERCURE_PORT}:80
    environment:
      SERVER_NAME: ':80'
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost
    command: /usr/bin/caddy run --config /etc/caddy/Caddyfile.dev

