version: "3.4"

services:
  caddy:
    restart: unless-stopped
    environment:
      CADDY_RUN: "prod"
    networks:
      - main_network
      - default

  php:
    restart: unless-stopped
    build:
      target: php_prod

  mercure:
    restart: unless-stopped
    networks:
      - main_network
      - default

networks:
  main_network:
    external: true
  default:
    external: false
