name: ${PROJECT_NAME}

services:
  caddy:
    image: ${PROJECT_NAME}_caddy
    container_name: ${PROJECT_NAME}_caddy
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: caddy
    depends_on:
      - php
    volumes:
      - ../:/var/www/app

  mysql:
    image: mysql:8.1
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql

  php:
    image: ${PROJECT_NAME}_php
    container_name: ${PROJECT_NAME}_php
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: php_dev
    depends_on:
      - mysql
    volumes:
      - ../:/var/www/app

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    container_name: ${PROJECT_NAME}_mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/healthz"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - mercure_data:/data
      - mercure_config:/config
###< symfony/mercure-bundle ###

volumes:
  mysql_volume:
  mercure_data:
  mercure_config:
